### ISSUE TITLE
dolphin-emu.org on the list?

### ISSUE THREAD

**Issue by ineffyble** [FediFence/fedifence#6]
Very confused as to how dolphin-emu.org ended up on this list.

From what I can tell, social.dolphin-emu.org (the relevant instance), has a single user with 7 posts, which is the official account of the emulator in question.

**Comment by jazmichaelking** [comment]
Thank you for raising the issue, we are looking into it and will report back as soon as possible.

**Comment by jazmichaelking** [comment]
The server in question is a weak positive in our criteria but was included on a higher-tier list of required blocks. We have communicated with the server administrator and will be removing the entry, thanks for your feedback.
