### ISSUE TITLE
mastodon.tech?

### ISSUE THREAD

**Issue by twilde** [FediFence/fedifence#8]
At a first look mastodon.tech seems like it has decent rules / CoC, I don't recall having seen them on Fediblock or any of the other usual places I'd look, can you please clarify their inclusion on the list?

**Comment by jazmichaelking** [comment]
The server in question is a strong positive in our criteria and remains included on the blocklist. Thanks for your feedback.

**Comment by twilde** [comment]
Can you provide any more details? Your criteria are sufficiently broad that it is ~impossible to independently verify something as generic as "strong positive in our criteria".
