### ISSUE TITLE
Clarify criteria and provide/attach reasons for listed domains

### ISSUE THREAD

**Issue by trwnh** [FediFence/fedifence#9]
In contrast with other lists such as rapidblock.org, which list their reasons next to each block and are generally sensible (with by my count only 2 questionable entries out of 157), I found myself questioning several of the inclusions in the current list, with about a 6% rate for what I would consider false positives (up to maybe ~18 domains of the current 300 or so). This is significantly higher than the approximately 1% rate for rapidblock.org's list.

I would like to not draw any judgements based on pure conjecture and without any evidence, so I am filing this issue to ask for clarification on your criteria -- what counts as a "weak positive" or a "strong positive", and what are you using to derive these signals? If you have any sources or other documentation it would be helpful for people to reason about this blocklist.

**Comment by jazmichaelking** [comment]
While we understand that people will be curious, we aren't ready to share our criteria at the moment.  We're taking the feedback we've received so far and using that to refine our evaluation process.  We will likely be making more changes to the list in the short term, and we hope to soon reach point where we are confident in the long term reliability of the list.

**Comment by jazmichaelking** [comment]
Blocklists are now pooled from consensus sources
